In [7]:
from __future__ import print_function, division

%matplotlib inline
%precision 3

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import correlate2d

import thinkplot

from matplotlib import rc
rc('animation', html='html5')

In [8]:
kernel = np.array([[1, 1, 1],
                   [1,10, 1],
                   [1, 1, 1]])
table = np.zeros(20, dtype=np.uint8)
table[[3, 12, 13]] = 1


In [13]:
def step(arr, table, kernel):
    """Executes one time step."""
    c = correlate2d(arr, kernel, mode='same')
    arr = table[c]
    print(arr)
    
a = np.random.randint(2, size=(10, 10)).astype(np.uint8)
print(a)
step(a, table, kernel)

[[1 0 0 0 0 1 0 0 1 1]
 [1 0 0 1 0 1 0 1 0 0]
 [1 1 1 0 0 0 0 1 0 0]
 [1 0 0 1 0 1 1 1 0 0]
 [1 0 1 1 1 1 1 0 0 1]
 [0 0 0 0 0 0 1 0 1 1]
 [0 1 0 0 0 1 1 0 1 0]
 [1 1 1 1 1 0 1 1 1 0]
 [1 1 0 1 1 0 0 0 0 1]
 [0 1 0 0 0 1 1 1 1 0]]
[[0 0 0 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 0 1 0 0]
 [1 0 1 1 0 1 0 1 1 0]
 [1 0 0 0 0 0 0 1 1 0]
 [0 1 1 1 0 0 0 0 0 1]
 [0 1 1 1 0 0 0 0 1 1]
 [1 1 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 0 0 0 1]
 [1 1 1 0 1 1 1 1 1 0]]


In [15]:
print(a)
def step(arr):
    """Executes one time step."""
    kernel = np.array([[1, 1, 1],
                   [1,1, 1],
                   [1, 1, 1]])
    table = np.zeros(20, dtype=np.uint8)
    table[[1,3,5,7,9]] = 1
    c = correlate2d(arr, kernel, mode='same')
    arr = table[c]
    print(arr)
    
step(a)
    

[[1 0 0 0 0 1 0 0 1 1]
 [1 0 0 1 0 1 0 1 0 0]
 [1 1 1 0 0 0 0 1 0 0]
 [1 0 0 1 0 1 1 1 0 0]
 [1 0 1 1 1 1 1 0 0 1]
 [0 0 0 0 0 0 1 0 1 1]
 [0 1 0 0 0 1 1 0 1 0]
 [1 1 1 1 1 0 1 1 1 0]
 [1 1 0 1 1 0 0 0 0 1]
 [0 1 0 0 0 1 1 1 1 0]]
[[0 0 1 1 1 0 1 0 1 0]
 [0 1 1 0 1 0 0 1 0 0]
 [0 1 0 1 0 1 0 0 1 0]
 [0 0 1 1 1 1 0 0 1 1]
 [0 1 1 0 1 0 0 1 0 1]
 [0 1 1 1 0 0 1 1 0 0]
 [1 0 0 1 1 1 1 1 1 0]
 [1 0 0 1 1 1 0 1 0 1]
 [1 0 0 1 1 1 1 0 1 1]
 [1 1 1 0 1 1 1 1 1 0]]


In [9]:
from scipy.stats import linregress
import numpy as np
v = [1, 3, 5]
m = [3, 6, 9]
for ys in [v, m]:
    p = linregress(np.log(v), np.log(ys))
print p[0]

0.674383290147
